### ISSUE TITLE
pip 0.2.8 broken

### ISSUE THREAD

**Issue by drozzy** [jxx123/simglucose#72]
The 0.2.8 version does not install for me
0.2.7 still works.

```
Collecting simglucose==0.2.8
  Using cached simglucose-0.2.8.tar.gz (600 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-htmoxn_c/simglucose_8ebacb09a20d4579b013c17371400350/setup.py", line 11, in <module>
          reqs = parse_requirements("requirements.txt")
        File "/tmp/pip-install-htmoxn_c/simglucose_8ebacb09a20d4579b013c17371400350/setup.py", line 6, in parse_requirements
          with open(filename) as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

```

**Comment by jxx123** [comment]
Sorry I am aware of this issue. Fix will soon be released. Thanks!

**Comment by jxx123** [comment]
The pip should be fixed. Install 0.2.9 instead.
